/*
 * default_dynlib.c
 *
 * Resolving dynamic imports of the .so.
 *
 * Copyright (C) 2021 Andy Nguyen
 * Copyright (C) 2021 Rinnegatamante
 * Copyright (C) 2022 Volodymyr Atamanenko
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

// Disable IDE complaints about _identifiers and global interfaces
#pragma ide diagnostic ignored "bugprone-reserved-identifier"
#pragma ide diagnostic ignored "cppcoreguidelines-interfaces-global-init"

#include "default_dynlib.h"

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <inttypes.h>
#include <math.h>
#include <netdb.h>
#include <string.h>
#include <wchar.h>
#include <wctype.h>
#include <zlib.h>

#include <sys/stat.h>
#include <sys/unistd.h>
#include <sys/socket.h>
#include <sys/time.h>

#include <psp2/kernel/clib.h>

#include <SLES/OpenSLES.h>
#include <SLES/OpenSLES_Android.h>

#include "glutil.h"
#include "libc_bridge.h"

#include "reimpl/env.h"
#include "reimpl/io.h"
#include "reimpl/log.h"
#include "reimpl/mem.h"
#include "reimpl/sys.h"
#include "reimpl/pthr.h"

extern void * _ZNSt9exceptionD2Ev;
extern void * _ZSt17__throw_bad_allocv;
extern void * _ZSt9terminatev;
extern void * _ZdaPv;
extern void * _ZdlPv;
extern void * _Znaj;
extern void * __cxa_allocate_exception;
extern void * __cxa_begin_catch;
extern void * __cxa_end_catch;
extern void * __cxa_free_exception;
extern void * __cxa_rethrow;
extern void * __cxa_throw;
extern void * __gxx_personality_v0;
extern void *_ZNSt8bad_castD1Ev;
extern void *_ZTISt8bad_cast;
extern void *_ZTISt9exception;
extern void *_ZTVN10__cxxabiv117__class_type_infoE;
extern void *_ZTVN10__cxxabiv120__si_class_type_infoE;
extern void *_ZTVN10__cxxabiv121__vmi_class_type_infoE;
extern void *_Znwj;
extern void *__aeabi_atexit;
extern void *__cxa_atexit;
extern void *__cxa_finalize;
extern void *__cxa_pure_virtual;
extern void *__gnu_unwind_frame;
extern void *__stack_chk_fail;
extern void *__stack_chk_guard;

static char *__ctype_ = (char *)&_ctype_; // NOLINT(cppcoreguidelines-interfaces-global-init)
static FILE __sF_fake[0x100][3];

// NOLINT(cppcoreguidelines-interfaces-global-init)
so_default_dynlib default_dynlib[SO_DYNLIB_LENGTH] = {
    { "AAssetManager_fromJava", (uintptr_t)&retNULL},
    { "AAssetManager_open", (uintptr_t)&AAssetManager_open},
    { "AAsset_close", (uintptr_t)&retNULL},
    { "AAsset_getLength", (uintptr_t)&retNULL},
    { "AAsset_getLength64", (uintptr_t)&retNULL},
    { "AAsset_getRemainingLength", (uintptr_t)&retNULL},
    { "AAsset_read", (uintptr_t)&retNULL},
    { "AAsset_seek", (uintptr_t)&retNULL},
    { "AAsset_seek64", (uintptr_t)&retNULL},
    { "AConfiguration_delete", (uintptr_t)&retNULL},
    { "AConfiguration_fromAssetManager", (uintptr_t)&retNULL},
    { "AConfiguration_getCountry", (uintptr_t)&retNULL},
    { "AConfiguration_getLanguage", (uintptr_t)&retNULL},
    { "AConfiguration_getUiModeType", (uintptr_t)&retNULL},
    { "AConfiguration_new", (uintptr_t)&retNULL},
    { "ALooper_forThread", (uintptr_t)&retNULL},
    { "ALooper_pollAll", (uintptr_t)&retNULL},
    { "ALooper_prepare", (uintptr_t)&retNULL},
    { "ANativeWindow_fromSurface", (uintptr_t)&retNULL},
    { "ANativeWindow_getHeight", (uintptr_t)&retNULL},
    { "ANativeWindow_getWidth", (uintptr_t)&retNULL},
    { "ANativeWindow_release", (uintptr_t)&retNULL},
    { "ANativeWindow_setBuffersGeometry", (uintptr_t)&retNULL},
    { "ASensorEventQueue_disableSensor", (uintptr_t)&retNULL},
    { "ASensorEventQueue_enableSensor", (uintptr_t)&retNULL},
    { "ASensorEventQueue_getEvents", (uintptr_t)&retNULL},
    { "ASensorEventQueue_setEventRate", (uintptr_t)&retNULL},
    { "ASensorManager_createEventQueue", (uintptr_t)&retNULL},
    { "ASensorManager_destroyEventQueue", (uintptr_t)&retNULL},
    { "ASensorManager_getInstance", (uintptr_t)&retNULL},
    { "ASensorManager_getSensorList", (uintptr_t)&retNULL},
    { "ASensor_getMinDelay", (uintptr_t)&retNULL},
    { "ASensor_getName", (uintptr_t)&retNULL},
    { "ASensor_getType", (uintptr_t)&retNULL},
    { "SL_IID_ANDROIDSIMPLEBUFFERQUEUE", (uintptr_t)&SL_IID_ANDROIDSIMPLEBUFFERQUEUE },
    { "SL_IID_ENGINE", (uintptr_t)&SL_IID_ENGINE },
    { "SL_IID_PLAY", (uintptr_t)&SL_IID_PLAY },
    { "SL_IID_RECORD", (uintptr_t)&SL_IID_RECORD },
    { "SL_IID_VOLUME", (uintptr_t)&SL_IID_VOLUME },
    { "_ZNSt8bad_castD1Ev", (uintptr_t)&_ZNSt8bad_castD1Ev },
    { "_ZNSt9exceptionD2Ev", (uintptr_t)&_ZNSt9exceptionD2Ev},
    { "_ZSt17__throw_bad_allocv", (uintptr_t)&_ZSt17__throw_bad_allocv},
    { "_ZSt9terminatev", (uintptr_t)&_ZSt9terminatev},
    { "_ZTISt8bad_cast", (uintptr_t)&_ZTISt8bad_cast },
    { "_ZTISt9exception", (uintptr_t)&_ZTISt9exception },
    { "_ZTVN10__cxxabiv117__class_type_infoE", (uintptr_t)&_ZTVN10__cxxabiv117__class_type_infoE },
    { "_ZTVN10__cxxabiv120__si_class_type_infoE", (uintptr_t)&_ZTVN10__cxxabiv120__si_class_type_infoE },
    { "_ZTVN10__cxxabiv121__vmi_class_type_infoE", (uintptr_t)&_ZTVN10__cxxabiv121__vmi_class_type_infoE },
    { "_ZdaPv", (uintptr_t)&_ZdaPv},
    { "_ZdlPv", (uintptr_t)&_ZdlPv},
    { "_Znaj", (uintptr_t)&_Znaj},
    { "_Znwj", (uintptr_t)&_Znwj},
    { "__aeabi_atexit", (uintptr_t)&__aeabi_atexit },
    { "__aeabi_memclr", (uintptr_t)&sceClibMemclr},
    { "__aeabi_memclr4", (uintptr_t)&sceClibMemclr},
    { "__aeabi_memclr8", (uintptr_t)&sceClibMemclr},
    { "__aeabi_memcpy", (uintptr_t)&sceClibMemcpy },
    { "__aeabi_memcpy4", (uintptr_t)&sceClibMemcpy},
    { "__aeabi_memcpy8", (uintptr_t)&sceClibMemcpy},
    { "__aeabi_memmove", (uintptr_t)&sceClibMemmove},
    { "__aeabi_memmove4", (uintptr_t)&sceClibMemmove},
    { "__aeabi_memmove8", (uintptr_t)&sceClibMemmove},
    { "__aeabi_memset", (uintptr_t)&sceClibMemset},
    { "__aeabi_memset8", (uintptr_t)&sceClibMemset},
    { "__android_log_print", (uintptr_t)&android_log_print },
    { "__android_log_vprint", (uintptr_t)&android_log_vprint },
    { "__android_log_write", (uintptr_t)&android_log_write },
    { "__assert2", (uintptr_t)&assert2},
    { "__cxa_allocate_exception", (uintptr_t)&__cxa_allocate_exception},
    { "__cxa_atexit", (uintptr_t)&__cxa_atexit },
    { "__cxa_begin_catch", (uintptr_t)&__cxa_begin_catch},
    { "__cxa_end_catch", (uintptr_t)&__cxa_end_catch},
    { "__cxa_finalize", (uintptr_t)&__cxa_finalize },
    { "__cxa_free_exception", (uintptr_t)&__cxa_free_exception},
    { "__cxa_pure_virtual", (uintptr_t)&__cxa_pure_virtual },
    { "__cxa_rethrow", (uintptr_t)&__cxa_rethrow},
    { "__cxa_throw", (uintptr_t)&__cxa_throw},
    { "__errno", (uintptr_t)&__errno },
    { "__gnu_unwind_frame", (uintptr_t)&__gnu_unwind_frame },
    { "__gxx_personality_v0", (uintptr_t)&__gxx_personality_v0},
    { "__mmap2", (uintptr_t)&mmap},
    { "__sF", (uintptr_t)&__sF_fake },
    { "__stack_chk_fail", (uintptr_t)&__stack_chk_fail },
    { "__stack_chk_guard", (uintptr_t)&__stack_chk_guard },
    { "__system_property_get", (uintptr_t)&system_property_get},
    { "_ctype_", (uintptr_t)&__ctype_ },
    { "_exit", (uintptr_t)&_exit},
    { "abort", (uintptr_t)&abort },
    { "acos", (uintptr_t)&acos },
    { "acosf", (uintptr_t)&acosf },
    { "asin", (uintptr_t)&asin },
    { "asinf", (uintptr_t)&asinf },
    { "atan", (uintptr_t)&atan },
    { "atan2", (uintptr_t)&atan2 },
    { "atan2f", (uintptr_t)&atan2f },
    { "atanf", (uintptr_t)&atanf },
    { "atoi", (uintptr_t)&atoi },
    { "atoll", (uintptr_t)&atoll },
    { "bsd_signal", (uintptr_t)&signal},
    { "bsearch", (uintptr_t)&bsearch },
    { "btowc", (uintptr_t)&btowc },
    { "calloc", (uintptr_t)&calloc },
    { "ceil", (uintptr_t)&ceil },
    { "ceilf", (uintptr_t)&ceilf },
    { "clearerr", (uintptr_t)&clearerr },
    { "clock_gettime", (uintptr_t)&clock_gettime_soloader },
    { "close", (uintptr_t)&close_soloader },
    { "connect", (uintptr_t)&connect},
    { "cos", (uintptr_t)&cos },
    { "cosf", (uintptr_t)&cosf },
    { "cosh", (uintptr_t)&cosh },
    { "crc32", (uintptr_t)&crc32 },
    { "dlopen", (uintptr_t)&ret0 },
    { "exit", (uintptr_t)&exit },
    { "exp", (uintptr_t)&exp },
    { "exp2", (uintptr_t)&exp2 },
    { "expf", (uintptr_t)&expf },
    { "fclose", (uintptr_t)&fclose },
    { "fcntl", (uintptr_t)&ret0 },
    { "fdopen", (uintptr_t)&fdopen },
    { "feof", (uintptr_t)&feof},
    { "ferror", (uintptr_t)&ferror },
    { "fflush", (uintptr_t)&fflush },
    { "fgets", (uintptr_t)&fgets },
    { "floor", (uintptr_t)&floor },
    { "floorf", (uintptr_t)&floorf },
    { "fmod", (uintptr_t)&fmod },
    { "fmodf", (uintptr_t)&fmodf },
    { "fopen", (uintptr_t)&fopen_soloader },
    { "fprintf", (uintptr_t)&fprintf },
    { "fputc", (uintptr_t)&fputc },
    { "fputs", (uintptr_t)&fputs },
    { "fread", (uintptr_t)&fread },
    { "free", (uintptr_t)&free },
    { "freeaddrinfo", (uintptr_t)&freeaddrinfo},
    { "frexp", (uintptr_t)&frexp },
    { "frexpf", (uintptr_t)&frexpf },
    { "fseek", (uintptr_t)&fseek },
    { "fseeko", (uintptr_t)&fseeko_soloader },
    { "fstat", (uintptr_t)&fstat_soloader },
    { "ftell", (uintptr_t)&ftell },
    { "ftello", (uintptr_t)&ftello_soloader },
    { "funopen", (uintptr_t)&funopen},
    { "fwrite", (uintptr_t)&fwrite },
    { "getaddrinfo", (uintptr_t)&getaddrinfo },
    { "getc", (uintptr_t)&getc },
    { "getenv", (uintptr_t)&getenv_soloader },
    { "gettimeofday", (uintptr_t)&gettimeofday },
    { "getwc", (uintptr_t)&getwc },

#ifdef DEBUG_GL
    { "glActiveTexture", (uintptr_t)&glActiveTexture_dbg},
    { "glAttachShader", (uintptr_t)&glAttachShader_dbg},
    { "glBindAttribLocation", (uintptr_t)&glBindAttribLocation_dbg},
    { "glBindBuffer", (uintptr_t)&glBindBuffer_dbg },
    { "glBindFramebuffer", (uintptr_t)&glBindFramebuffer_dbg},
    { "glBindTexture", (uintptr_t)&glBindTexture_dbg },
    { "glBlendEquationSeparate", (uintptr_t)&glBlendEquationSeparate_dbg},
    { "glBlendFunc", (uintptr_t)&glBlendFunc_dbg },
    { "glBlendFuncSeparate", (uintptr_t)&glBlendFuncSeparate_dbg},
    { "glBufferData", (uintptr_t)&glBufferData_dbg },
    { "glClear", (uintptr_t)&glClear_dbg },
    { "glClearColor", (uintptr_t)&glClearColor_dbg },
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glClearDepthf", (uintptr_t)&glClearDepthf_sfp },
#else
    { "glClearDepthf", (uintptr_t)&glClearDepthf_dbg },
#endif
    { "glCompileShader", (uintptr_t)&glCompileShader_dbg},
    { "glCompressedTexImage2D", (uintptr_t)&glCompressedTexImage2D_dbg },
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glCopyTexSubImage2D", (uintptr_t)&glCopyTexSubImage2D },
#else
    { "glCopyTexSubImage2D", (uintptr_t)&glCopyTexSubImage2D_dbg },
#endif
    { "glCreateProgram", (uintptr_t)&glCreateProgram_dbg},
    { "glCreateShader", (uintptr_t)&glCreateShader_dbg},
    { "glDeleteBuffers", (uintptr_t)&glDeleteBuffers_dbg },
    { "glDeleteFramebuffers", (uintptr_t)&glDeleteFramebuffers_dbg},
    { "glDeleteTextures", (uintptr_t)&glDeleteTextures_dbg },
    { "glDepthFunc", (uintptr_t)&glDepthFunc_dbg },
    { "glDepthMask", (uintptr_t)&glDepthMask_dbg },
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glDepthRangef", (uintptr_t) &glDepthRangef_sfp },
    { "glDetachShader", (uintptr_t)&glDetachShader},
#else
    { "glDepthRangef", (uintptr_t) &glDepthRangef_dbg },
    { "glDetachShader", (uintptr_t)&glDetachShader_dbg},
#endif
    { "glDisable", (uintptr_t)&glDisable_dbg },
    { "glDrawArrays", (uintptr_t)&glDrawArrays_dbg},
    { "glDrawElements", (uintptr_t)&glDrawElements_dbg },
    { "glEnable", (uintptr_t)&glEnable_dbg },
    { "glEnableVertexAttribArray", (uintptr_t)&glEnableVertexAttribArray_dbg},
    { "glFramebufferTexture2D", (uintptr_t)&glFramebufferTexture2D_dbg},
    { "glGenBuffers", (uintptr_t)&glGenBuffers_dbg },
    { "glGenFramebuffers", (uintptr_t)&glGenFramebuffers_dbg},
    { "glGenTextures", (uintptr_t)&glGenTextures_dbg },
    { "glGetError", (uintptr_t)&glGetError_dbg },
    { "glGetIntegerv", (uintptr_t)&glGetIntegerv_dbg},
    { "glGetProgramInfoLog", (uintptr_t)&glGetProgramInfoLog_dbg},
    { "glGetProgramiv", (uintptr_t)&glGetProgramiv_dbg},
    { "glGetShaderInfoLog", (uintptr_t)&glGetShaderInfoLog_dbg},
    { "glGetShaderiv", (uintptr_t)&glGetShaderiv_dbg},
    { "glGetString", (uintptr_t)&glGetString_dbg},
    { "glGetUniformLocation", (uintptr_t)&glGetUniformLocation_dbg},
    { "glLinkProgram", (uintptr_t)&glLinkProgram_dbg},
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glPixelStorei", (uintptr_t)&glPixelStorei },
    { "glShaderSource", (uintptr_t)&glShaderSource_dbg},
#else
    { "glPixelStorei", (uintptr_t)&glPixelStorei_dbg},
    { "glShaderSource", (uintptr_t)&glShaderSourceHook},
#endif
    { "glShaderSource", (uintptr_t)&glShaderSource_dbg},
    { "glTexImage2D", (uintptr_t)&glTexImage2D_dbg },
    { "glTexParameteri", (uintptr_t)&glTexParameteri_dbg },
    { "glTexSubImage2D", (uintptr_t)&glTexSubImage2D_dbg },
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glUniform1f", (uintptr_t)&glUniform1f_sfp},
    { "glUniform2f", (uintptr_t)&glUniform2f_sfp},
    { "glUniform4f", (uintptr_t)&glUniform4f_sfp},
#else
    { "glUniform1f", (uintptr_t)&glUniform1f_dbg},
    { "glUniform2f", (uintptr_t)&glUniform2f_dbg},
    { "glUniform4f", (uintptr_t)&glUniform4f_dbg},
#endif
    { "glUniform1i", (uintptr_t)&glUniform1i_dbg},
    { "glUseProgram", (uintptr_t)&glUseProgram_dbg},
    { "glVertexAttribPointer", (uintptr_t)&glVertexAttribPointer_dbg},
    { "glViewport", (uintptr_t)&glViewport_dbg },
#else // DEBUG_GL
    { "glActiveTexture", (uintptr_t)&glActiveTexture},
    { "glAttachShader", (uintptr_t)&glAttachShader},
    { "glBindAttribLocation", (uintptr_t)&glBindAttribLocation},
    { "glBindBuffer", (uintptr_t)&glBindBuffer },
    { "glBindFramebuffer", (uintptr_t)&glBindFramebuffer},
    { "glBindTexture", (uintptr_t)&glBindTexture },
    { "glBlendEquationSeparate", (uintptr_t)&glBlendEquationSeparate},
    { "glBlendFunc", (uintptr_t)&glBlendFunc },
    { "glBlendFuncSeparate", (uintptr_t)&glBlendFuncSeparate},
    { "glBufferData", (uintptr_t)&glBufferData },
    { "glClear", (uintptr_t)&glClear },
    { "glClearColor", (uintptr_t)&glClearColor },
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glClearDepthf", (uintptr_t)&glClearDepthf_sfp },
#else
    { "glClearDepthf", (uintptr_t)&glClearDepthf },
#endif
    { "glCompileShader", (uintptr_t)&ret0},
    { "glCompressedTexImage2D", (uintptr_t)&glCompressedTexImage2D },
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glCopyTexSubImage2D", (uintptr_t)&glCopyTexSubImage2D },
#else
    { "glCopyTexSubImage2D", (uintptr_t)&ret0 },
#endif
    { "glCreateProgram", (uintptr_t)&glCreateProgram},
    { "glCreateShader", (uintptr_t)&glCreateShader},
    { "glDeleteBuffers", (uintptr_t)&glDeleteBuffers },
    { "glDeleteFramebuffers", (uintptr_t)&glDeleteFramebuffers},
    { "glDeleteTextures", (uintptr_t)&glDeleteTextures },
    { "glDepthFunc", (uintptr_t)&glDepthFunc },
    { "glDepthMask", (uintptr_t)&glDepthMask },
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glDepthRangef", (uintptr_t) &glDepthRangef_sfp },
    { "glDetachShader", (uintptr_t)&glDetachShader},
#else
    { "glDepthRangef", (uintptr_t) &glDepthRangef },
    { "glDetachShader", (uintptr_t)&ret0},
#endif
    { "glDisable", (uintptr_t)&glDisable },
    { "glDrawArrays", (uintptr_t)&glDrawArrays},
    { "glDrawElements", (uintptr_t)&glDrawElements },
    { "glEnable", (uintptr_t)&glEnable },
    { "glEnableVertexAttribArray", (uintptr_t)&glEnableVertexAttribArray},
    { "glFramebufferTexture2D", (uintptr_t)&glFramebufferTexture2D},
    { "glGenBuffers", (uintptr_t)&glGenBuffers },
    { "glGenFramebuffers", (uintptr_t)&glGenFramebuffers},
    { "glGenTextures", (uintptr_t)&glGenTextures },
    { "glGetError", (uintptr_t)&glGetError },
    { "glGetIntegerv", (uintptr_t)&glGetIntegerv},
    { "glGetProgramInfoLog", (uintptr_t)&glGetProgramInfoLog},
    { "glGetProgramiv", (uintptr_t)&glGetProgramiv},
    { "glGetShaderInfoLog", (uintptr_t)&glGetShaderInfoLog},
    { "glGetShaderiv", (uintptr_t)&glGetShaderiv},
    { "glGetString", (uintptr_t)&glGetString},
    { "glGetUniformLocation", (uintptr_t)&glGetUniformLocation},
    { "glLinkProgram", (uintptr_t)&glLinkProgram},
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glPixelStorei", (uintptr_t)&glPixelStorei },
    { "glShaderSource", (uintptr_t)&glShaderSource},
#else
    { "glPixelStorei", (uintptr_t)&ret0},
    { "glShaderSource", (uintptr_t)&glShaderSourceHook},
#endif
    { "glShaderSource", (uintptr_t)&glShaderSource},
    { "glTexImage2D", (uintptr_t)&glTexImage2D },
    { "glTexParameteri", (uintptr_t)&glTexParameteri },
    { "glTexSubImage2D", (uintptr_t)&glTexSubImage2D },
#if GRAPHICS_API == GRAPHICS_API_PVR
    { "glUniform1f", (uintptr_t)&glUniform1f_sfp},
    { "glUniform2f", (uintptr_t)&glUniform2f_sfp},
    { "glUniform4f", (uintptr_t)&glUniform4f_sfp},
#else
    { "glUniform1f", (uintptr_t)&glUniform1f},
    { "glUniform2f", (uintptr_t)&glUniform2f},
    { "glUniform4f", (uintptr_t)&glUniform4f},
#endif
    { "glUniform1i", (uintptr_t)&glUniform1i},
    { "glUseProgram", (uintptr_t)&glUseProgram},
    { "glVertexAttribPointer", (uintptr_t)&glVertexAttribPointer},
    { "glViewport", (uintptr_t)&glViewport },
#endif // DEBUG_GL

    { "gmtime", (uintptr_t)&gmtime},
    { "gzopen", (uintptr_t)&ret0 },
    { "hid_close", (uintptr_t)&retNULL},
    { "hid_enumerate", (uintptr_t)&retNULL},
    { "hid_exit", (uintptr_t)&retNULL},
    { "hid_free_enumeration", (uintptr_t)&retNULL},
    { "hid_get_feature_report", (uintptr_t)&retNULL},
    { "hid_init", (uintptr_t)&retNULL},
    { "hid_open_path", (uintptr_t)&retNULL},
    { "hid_read", (uintptr_t)&retNULL},
    { "hid_read_timeout", (uintptr_t)&retNULL},
    { "hid_send_feature_report", (uintptr_t)&retNULL},
    { "hid_write", (uintptr_t)&retNULL},
    { "inflate", (uintptr_t)&inflate },
    { "inflateEnd", (uintptr_t)&inflateEnd },
    { "inflateInit_", (uintptr_t)&inflateInit_ },
    { "inflateReset", (uintptr_t)&inflateReset },
    { "isalnum", (uintptr_t)&isalnum },
    { "isalpha", (uintptr_t)&isalpha },
    { "isblank", (uintptr_t)&isblank},
    { "iscntrl", (uintptr_t)&iscntrl },
    { "isgraph", (uintptr_t)&isgraph},
    { "islower", (uintptr_t)&islower },
    { "isprint", (uintptr_t)&isprint },
    { "ispunct", (uintptr_t)&ispunct },
    { "isspace", (uintptr_t)&isspace },
    { "isupper", (uintptr_t)&isupper },
    { "iswalpha", (uintptr_t)&iswalpha },
    { "iswcntrl", (uintptr_t)&iswcntrl },
    { "iswctype", (uintptr_t)&iswctype },
    { "iswdigit", (uintptr_t)&iswdigit },
    { "iswdigit", (uintptr_t)&iswdigit },
    { "iswlower", (uintptr_t)&iswlower },
    { "iswprint", (uintptr_t)&iswprint },
    { "iswpunct", (uintptr_t)&iswpunct },
    { "iswspace", (uintptr_t)&iswspace },
    { "iswupper", (uintptr_t)&iswupper },
    { "iswxdigit", (uintptr_t)&iswxdigit },
    { "isxdigit", (uintptr_t)&isxdigit },
    { "ldexp", (uintptr_t)&ldexp },
    { "ldexpf", (uintptr_t)&ldexpf},
    { "localtime", (uintptr_t)&localtime},
    { "localtime_r", (uintptr_t)&localtime_r },
    { "log", (uintptr_t)&log },
    { "log10", (uintptr_t)&log10 },
    { "log10f", (uintptr_t)&log10f},
    { "logf", (uintptr_t)&logf},
    { "longjmp", (uintptr_t)&longjmp },
    { "lrand48", (uintptr_t)&lrand48 },
    { "lrint", (uintptr_t)&lrint },
    { "lrintf", (uintptr_t)&lrintf },
    { "lround", (uintptr_t)&lround},
    { "lroundf", (uintptr_t)&lroundf},
    { "lseek", (uintptr_t)&lseek },
    { "malloc", (uintptr_t)&malloc },
    { "mbrlen", (uintptr_t)&mbrlen},
    { "mbrtowc", (uintptr_t)&mbrtowc },
    { "memchr", (uintptr_t)&sceClibMemchr },
    { "memcmp", (uintptr_t)&memcmp },
    { "memcpy", (uintptr_t)&sceClibMemcpy },
    { "memmem", (uintptr_t)&memmem},
    { "memmove", (uintptr_t)&sceClibMemmove },
    { "memset", (uintptr_t)&sceClibMemset },
    { "mkdir", (uintptr_t)&mkdir },
    { "mktime", (uintptr_t)&mktime},
    { "mmap", (uintptr_t)&mmap },
    { "modf", (uintptr_t)&modf },
    { "munmap", (uintptr_t)&munmap },
    { "nanosleep", (uintptr_t)&nanosleep_soloader },
    { "open", (uintptr_t)&open_soloader },
    { "pow", (uintptr_t)&pow },
    { "powf", (uintptr_t)&powf },
    { "printf", (uintptr_t)&printf },
    { "pthread_attr_destroy", (uintptr_t)&pthread_attr_destroy_soloader },
    { "pthread_attr_init", (uintptr_t) &pthread_attr_init_soloader },
    { "pthread_attr_setdetachstate", (uintptr_t) &pthread_attr_setdetachstate_soloader },
    { "pthread_attr_setstacksize", (uintptr_t) &pthread_attr_setstacksize_soloader },
    { "pthread_cond_broadcast", (uintptr_t) &pthread_cond_broadcast_soloader},
    { "pthread_cond_destroy", (uintptr_t) &pthread_cond_destroy_soloader},
    { "pthread_cond_init", (uintptr_t) &pthread_cond_init_soloader},
    { "pthread_cond_signal", (uintptr_t) &pthread_cond_signal_soloader},
    { "pthread_cond_timedwait", (uintptr_t) &pthread_cond_timedwait_soloader},
    { "pthread_cond_wait", (uintptr_t) &pthread_cond_wait_soloader},
    { "pthread_create", (uintptr_t) &pthread_create_soloader },
    { "pthread_detach", (uintptr_t) &pthread_detach_soloader},
    { "pthread_equal", (uintptr_t) &pthread_equal_soloader},
    { "pthread_getschedparam", (uintptr_t) &pthread_getschedparam_soloader },
    { "pthread_getspecific", (uintptr_t)&pthread_getspecific },
    { "pthread_join", (uintptr_t) &pthread_join_soloader},
    { "pthread_key_create", (uintptr_t)&pthread_key_create },
    { "pthread_key_delete", (uintptr_t)&pthread_key_delete },
    { "pthread_mutex_destroy", (uintptr_t) &pthread_mutex_destroy_soloader },
    { "pthread_mutex_init", (uintptr_t) &pthread_mutex_init_soloader },
    { "pthread_mutex_lock", (uintptr_t) &pthread_mutex_lock_soloader },
    { "pthread_mutex_trylock", (uintptr_t) &pthread_mutex_trylock_soloader},
    { "pthread_mutex_unlock", (uintptr_t) &pthread_mutex_unlock_soloader },
    { "pthread_mutexattr_destroy", (uintptr_t) &pthread_mutexattr_destroy_soloader},
    { "pthread_mutexattr_init", (uintptr_t) &pthread_mutexattr_init_soloader},
    { "pthread_mutexattr_settype", (uintptr_t) &pthread_mutexattr_settype_soloader},
    { "pthread_once", (uintptr_t)&pthread_once },
    { "pthread_self", (uintptr_t) &pthread_self_soloader },
    { "pthread_setname_np", (uintptr_t) &pthread_setname_np_soloader },
    { "pthread_setschedparam", (uintptr_t) &pthread_setschedparam_soloader },
    { "pthread_setspecific", (uintptr_t)&pthread_setspecific },
    { "pthread_sigmask", (uintptr_t)&ret0},
    { "putc", (uintptr_t)&putc },
    { "putchar", (uintptr_t)&putchar},
    { "puts", (uintptr_t)&puts},
    { "putwc", (uintptr_t)&putwc },
    { "qsort", (uintptr_t)&qsort },
    { "raise", (uintptr_t)&raise},
    { "read", (uintptr_t)&read },
    { "realloc", (uintptr_t)&realloc },
    { "remove", (uintptr_t)&remove},
    { "rint", (uintptr_t)&rint },
    { "rmdir", (uintptr_t)&rmdir},
    { "round", (uintptr_t)&round},
    { "roundf", (uintptr_t)&roundf},
    { "scalbn", (uintptr_t)&scalbn},
    { "scalbnf", (uintptr_t)&scalbnf},
    { "sched_get_priority_max", (uintptr_t)&sched_get_priority_max},
    { "sched_get_priority_min", (uintptr_t)&sched_get_priority_min},
    { "sched_yield", (uintptr_t)&sched_yield},
    { "select", (uintptr_t)&select},
    { "sem_destroy", (uintptr_t) &sem_destroy_soloader},
    { "sem_getvalue", (uintptr_t) &sem_getvalue_soloader},
    { "sem_init", (uintptr_t) &sem_init_soloader},
    { "sem_post", (uintptr_t) &sem_post_soloader},
    { "sem_timedwait", (uintptr_t) &sem_timedwait_soloader},
    { "sem_trywait", (uintptr_t) &sem_trywait_soloader},
    { "sem_wait", (uintptr_t) &sem_wait_soloader},
    { "setenv", (uintptr_t)&ret0 },
    { "setjmp", (uintptr_t)&setjmp },
    { "setvbuf", (uintptr_t)&setvbuf },
    { "shutdown", (uintptr_t)&shutdown },
    { "sin", (uintptr_t)&sin },
    { "sincos", (uintptr_t)&sincos},
    { "sincosf", (uintptr_t)&sincosf},
    { "sinf", (uintptr_t)&sinf },
    { "sinh", (uintptr_t)&sinh },
    { "slCreateEngine", (uintptr_t)&slCreateEngine},
    { "snprintf", (uintptr_t)&snprintf },
    { "socket", (uintptr_t)&socket},
    { "sprintf", (uintptr_t)&sprintf },
    { "sqrt", (uintptr_t)&sqrt },
    { "sqrtf", (uintptr_t)&sqrtf },
    { "srand48", (uintptr_t)&srand48 },
    { "sscanf", (uintptr_t)&sscanf },
    { "stat", (uintptr_t)&stat_soloader },
    { "strcasecmp", (uintptr_t)&strcasecmp },
    { "strcat", (uintptr_t)&strcat },
    { "strchr", (uintptr_t)&strchr },
    { "strcmp", (uintptr_t)&sceClibStrcmp },
    { "strcoll", (uintptr_t)&strcoll },
    { "strcpy", (uintptr_t)&strcpy },
    { "strcspn", (uintptr_t)&strcspn },
    { "strerror", (uintptr_t)&strerror },
    { "strerror_r", (uintptr_t)&strerror_r},
    { "strftime", (uintptr_t)&strftime },
    { "strlcat", (uintptr_t)&strlcat},
    { "strlcpy", (uintptr_t)&strlcpy},
    { "strlen", (uintptr_t)&strlen },
    { "strncasecmp", (uintptr_t)&sceClibStrncasecmp },
    { "strncat", (uintptr_t)&sceClibStrncat },
    { "strncmp", (uintptr_t)&sceClibStrncmp },
    { "strncpy", (uintptr_t)&sceClibStrncpy },
    { "strnlen", (uintptr_t)&strnlen},
    { "strpbrk", (uintptr_t)&strpbrk },
    { "strrchr", (uintptr_t)&sceClibStrrchr },
    { "strstr", (uintptr_t)&sceClibStrstr },
    { "strtod", (uintptr_t)&strtod },
    { "strtoimax", (uintptr_t)&strtoimax },
    { "strtok_r", (uintptr_t)&strtok_r},
    { "strtol", (uintptr_t)&strtol },
    { "strtoll", (uintptr_t)&strtoll },
    { "strtoul", (uintptr_t)&strtoul },
    { "strtoull", (uintptr_t)&strtoull },
    { "strtoumax", (uintptr_t)&strtoumax },
    { "strxfrm", (uintptr_t)&strxfrm },
    { "syscall", (uintptr_t)&syscall },
    { "sysconf", (uintptr_t)&ret0 },
    { "system", (uintptr_t)&system},
    { "tan", (uintptr_t)&tan },
    { "tanf", (uintptr_t)&tanf },
    { "tanh", (uintptr_t)&tanh },
    { "time", (uintptr_t)&time },
    { "tolower", (uintptr_t)&tolower },
    { "toupper", (uintptr_t)&toupper },
    { "towlower", (uintptr_t)&towlower },
    { "towupper", (uintptr_t)&towupper },
    { "trunc", (uintptr_t)&trunc},
    { "truncf", (uintptr_t)&truncf},
    { "ungetc", (uintptr_t)&ungetc },
    { "ungetwc", (uintptr_t)&ungetwc },
    { "usleep", (uintptr_t)&usleep },
    { "vasprintf", (uintptr_t)&vasprintf},
    { "vfprintf", (uintptr_t)&vfprintf },
    { "vprintf", (uintptr_t)&vprintf },
    { "vsnprintf", (uintptr_t)&vsnprintf },
    { "vsprintf", (uintptr_t)&vsprintf },
    { "vsscanf", (uintptr_t)&vsscanf},
    { "vswprintf", (uintptr_t)&vswprintf },
    { "wcrtomb", (uintptr_t)&wcrtomb },
    { "wcscasecmp", (uintptr_t)&wcscasecmp},
    { "wcscmp", (uintptr_t)&wcscmp },
    { "wcscoll", (uintptr_t)&wcscoll },
    { "wcsftime", (uintptr_t)&wcsftime },
    { "wcslcat", (uintptr_t)&wcslcat},
    { "wcslcpy", (uintptr_t)&wcslcpy},
    { "wcslen", (uintptr_t)&wcslen },
    { "wcsncasecmp", (uintptr_t)&wcsncasecmp},
    { "wcsncpy", (uintptr_t)&wcsncpy },
    { "wcsxfrm", (uintptr_t)&wcsxfrm },
    { "wctob", (uintptr_t)&wctob },
    { "wctype", (uintptr_t)&wctype },
    { "wmemchr", (uintptr_t)&wmemchr },
    { "wmemcmp", (uintptr_t)&wmemcmp },
    { "wmemcpy", (uintptr_t)&wmemcpy },
    { "wmemmove", (uintptr_t)&wmemmove },
    { "wmemset", (uintptr_t)&wmemset },
    { "write", (uintptr_t)&write_soloader },
};
